title: MOHAMAD FAKHRUL IKHROM # your name (or website title) here
logo: "/images/camera.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Peserta Studi Independen Data Analitics Zenius Batch III
  <br><br>
  Mahasiswa Sekolah Tinggi Manajemen dan Ilmu Komputer (STMIK) INDO DAYA SUVANA JAKARTA 
  <br><br>
  <a href="https://www.linkedin.com/in/mohamad-fakhrul-ikhrom-4a6ba324b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
